name: GetUserReposList
on:
  push:
    branches:
    - main
    - release/*
  schedule:
    # Runs every 30 minutes
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.GH_TOKEN }}
          user: 'laiyopufafa'
          # (default)max_page: 10
          # (default)block_list:
          # (default)allow_empty: false
          # (default)allow_archived: true

      - name: Echo Output
        run: |
          echo repoList_ALL: ${{steps.repo.outputs.repoList_ALL}}
          
      - name: Get Scorecard
        id: scores
        uses: ossf/scorecard@main
        with: 
          args: '--repo: https://github.com/ossf/scorecard --format: json'
          
          
          
      - name: Echo Output
        run: |
          echo repoList_ALL: ${{steps.scores.outputs}}
          
      - name: Score Repositroies
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export GITHUB_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
          scorecard --repo https://github.com/ossf/scorecard --format json
