name: "repo list in json format"

on:
  push:
    branches:
    - main
    - release/*
  schedule:
    # Runs every 30 minutes
    - cron: '0/30 0/1 * * *'
  workflow_dispatch:
  
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Organization Repositories
        id: get_org_repos
        uses: firenza/get-organization-repositories@v1.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          organization: 'openeuler-mirror'

      - name: Show org repos
        shell: bash
        run: echo ${{ steps.get_org_repos.outputs }}
