name: "repo list in json format"

on:
  push:
    branches:
    - main
    - release/*
  schedule:
    # Runs every 30 minutes
    - cron: '0/30 0/1 * * *'
  workflow_dispatch:
  
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/get-organization-repositories@v1
        with:
          github-organization: 'github'
