name: ScorecardForOpenHarmony
on:
  push:
    branches:
    - main
    - release/*
  schedule:
    # Runs every 30 minutes
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.GH_TOKEN }}
          # user: 'laiyoufafa'
          # (default)max_page: 10
          # (default)block_list:
          # (default)allow_empty: false
          # (default)allow_archived: true
      
      - name: current PATH
        run: pwd
     
          
      - name: Get Scorecard
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh repo clone ossf/scorecard /tmp/scorecard
          cd /tmp/scorecard
          make build
          export PATH=$PATH:/tmp/scorecard
          
          
          
      - name: Echo Output
        run: |
           echo repoList_ALL: ${{steps.scores.outputs.repoList_ALL}}
          
      - name: Score Repositroies
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          scorecard --repo https://github.com/ossf/scorecard --format json
