name: ScorecardForOpenHarmony
on:
  push:
    branches:
    - main
    - release/*
  schedule:
    # Runs every 30 minutes
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.GH_TOKEN }}
          # user: 'laiyoufafa'
          # (default)max_page: 10
          # (default)block_list:
          # (default)allow_empty: false
          # (default)allow_archived: true
          
      # /home/runner/work/ScoreCardActionForOpenHarmony/ScoreCardActionForOpenHarmony
      # - name: current PATH
      #  run: pwd
     
          
      - name: Get Scorecard
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOWNLOAD_URL: https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
          BASE_URL: https://github.com/ossf/scorecard/releases/download/
          RAW_FILE_NAME: scorecard_4.10.5_linux_amd64.tar.gz
          EXCUTE_FILE_NAME: scorecard_linux_amd64
        run: |
          wget ${{ DOWNLOAD_URL }}
          chmod 777 ${{ RAW_FILE_NAME }}
          tar -zxvf ${{ RAW_FILE_NAME }}
          cp ${{ EXECUTE_FILE_NAME }} scorecard
          export PATH=$PATH:/home/runner/work/ScoreCardActionForOpenHarmony/ScoreCardActionForOpenHarmony/
          
      - name: Echo Output
        run: |
           echo repoList_ALL: ${{steps.scores.outputs.repoList_ALL}}
          
      - name: Score Repositroies
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export PATH=$PATH:/home/runner/work/ScoreCardActionForOpenHarmony/ScoreCardActionForOpenHarmony/
          scorecard --repo https://github.com/ossf/scorecard --format json
