name: Update awesome list

on:
 push:
  branches:
  - main
  - release/*
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome generator
        uses: simonecorsi/mawesome@latest
        with:
          api-token: ${{ secrets.GH_TOKEN }}
          github-email: ${{ secrets.GH_EMAIL }}
          github-name: ${{ secrets.GH_OWNER }}
