name: TestGetUserReposList
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.GH_TOKEN }}
          user: 'laiyoufafa'
          max_page: 10
          block_list:
          allow_empty: false
          allow_archived: true
